2 style
Quaaludees/react-hw pull request #2
Opened 2024-08-09 22:06 UTC by Quaaludees

2024-08-11 20:30 UTC, Levitinn requested changes

2024-08-11 20:30 UTC, Levitinn commented on src/components/Header/Header.jsx
> +        { href: '#', title: user?.name, icon: <UserIcon />, isHidden: !user },
user?.name ты передаешь отсюда. а правильнее наверно, логику отображения имени/войти засунуть в сам компонент кнопки, так как она относится именно к ней

2024-08-11 20:30 UTC, Levitinn commented on src/components/SearchFilms/SearchFilms.jsx
>                  <FilmCard key={filmName} filmName={filmName} poster={poster} isFavorites={isFavorites} count={count}/>
filmName не подходит для key. могут быть фильмы с одинаковым названием

2024-08-11 20:30 UTC, Levitinn commented on src/components/SearchFilms/SearchFilms.jsx
>              {FILMS_DATA.map(({filmName,poster,count, isFavorites}) => (
нет проверки что FILMS_DATA может быть пустым

2024-08-11 20:30 UTC, Levitinn commented on src/components/SearchFilms/SearchFilms.jsx
кажется, поиск и компонент, где ты выводишь фильмы, должны быть раздельными компонентами

2024-08-11 20:30 UTC, Levitinn commented on src/components/FilmCard/FilmCard.jsx
>  const FilmCard = ({count, poster, filmName, isFavorites}) => {
нет проверки на то, что какой либо из пропсов может быть undefined.

2024-08-11 23:07 UTC, Quaaludees commented on src/components/SearchFilms/SearchFilms.jsx
>                  <FilmCard key={filmName} filmName={filmName} poster={poster} isFavorites={isFavorites} count={count}/>
+

2024-08-11 23:08 UTC, Quaaludees commented on src/components/Header/Header.jsx
> +        { href: '#', title: user?.name, icon: <UserIcon />, isHidden: !user },
Я думала хорошим тоном является: делать компонент "тупым" т.е ему неважно где и как он просто отрисовывает, а в этом случае есть "хедер" который в свою очередь рисует просто список кнопок. И наверное логичнее всего иметь централизованную точку управления списком.

2024-08-11 23:08 UTC, Quaaludees commented on src/components/SearchFilms/SearchFilms.jsx
>              {FILMS_DATA.map(({filmName,poster,count, isFavorites}) => (
Да, я хочу добавить, когда будет дальше отрисовка страницы "не найдено".  Пока добавлен optional chaining.

2024-08-11 23:08 UTC, Quaaludees commented on src/components/SearchFilms/SearchFilms.jsx
+

2024-08-13 20:09 UTC, Levitinn commented on src/components/Header/Header.jsx
> +        { href: '#', title: user?.name, icon: <UserIcon />, isHidden: !user },
так пусть он и будет тупым и рендерит только список кнопок. я говорю о том, что ты передаешь ему прямо "войти\выйти", а эта логика зависит от того, авторизован ли пользователь. и эту логику правильнее держать внутри компонента, а не снаружи, так как она относится только к нему.

так же, важно отметить, что твой menuItem тоже не лучшее решение, по той причине, что объекты в нем содержат не строгую типизацию, а именно, какой то объект может иметь href, а другой не иметь, а так же другие поля либо есть либо нет. это лишняя неочевидная логика ради, всего лишь, четырех пунктов меню

2024-08-13 20:14 UTC, Levitinn commented on src/components/FilmCard/FilmCard.jsx
>                      <FavIcon/>
иконка и текст "в избранном\в избранное" - не разделимы друг от друга, так и напрашивается засунуть это в отдельный компонент

2024-08-13 20:14 UTC, Levitinn commented on src/components/SearchFilms/SearchFilms.jsx
>              {FILMS_DATA.map(({filmName,poster,count, isFavorites}) => (
это стоить сделать прямо сейчас, так как сервер может не ответить при самой первой загрузке страницы, без какого либо поиска от юзера, и тогда страница не должна упасть

2024-08-13 20:14 UTC, Levitinn requested changes
добавил комментарии

2024-08-14 19:12 UTC, Quaaludees commented on src/components/Header/Header.jsx
> +        { href: '#', title: user?.name, icon: <UserIcon />, isHidden: !user },
Я не понимаю и не согласна! Т.к в Header я определяю для множества menuItems идет завязка на: авторизован пользователь или нет, проще конфигурировать эти самые Items в одном месте. По поводу href как я понимаю он исчезнет со временем при подключении роутинга и все завяжется на onClick.
А если создавать отдельный компонент который будет менять tittle/etc в зависимости от авторизован пользователь  или нет, зачем вообще(?) если в компонент отрисовки добавляется логику проверки на авторизацию. 
+ в пользу моего решения: это удобное управление скрытием элемента. 4 новых компонента против лаконичного решения в одном месте на пару строк. Явно будет проще редактировать из одного места, чем потом в 4 компонентах рыскать. 


`interface IMenuItems {
    onClick: () => void
    title: string
    icon: ReactNode
    href?: string //рудимент который скорее всего изчезнет в дальнейшем
    isHidden?: boolean
    count?: number //можно убрать сделая тайтл ReactNode
}`

2024-08-14 19:15 UTC, Quaaludees commented on src/components/FilmCard/FilmCard.jsx
>                      <FavIcon/>
Я не понимаю, зачем плодить столько компонентов. Чем тернарное выражение плохо на примере проекта "Фильмы"?

2024-08-15 20:47 UTC, Levitinn commented on src/components/Header/Header.jsx
> +        { href: '#', title: user?.name, icon: <UserIcon />, isHidden: !user },
когда ты начнешь прикручивать авторизацию, где будешь хранить ее логику? в хедере? это будет не верно, так как авторизация никак хедера не касается и тебе нужно будет вытаскивать ее логику в отдельный компонент, который будет авторизовывать\деавторизовывать, но при этом, текст будет вынесен из этого компонента?

2024-08-15 20:49 UTC, Levitinn commented on src/components/FilmCard/FilmCard.jsx
>                      <FavIcon/>
по той же причине, что и с авторизацией. логику добавления\удаления в избранное будешь держать FilmCard? нет, тебе придется вынести это в отдельный компонент и описать логику в нем

2024-08-15 20:50 UTC, Levitinn requested changes
ответил

2024-08-15 21:17 UTC, Quaaludees commented on src/components/Header/Header.jsx
> +        { href: '#', title: user?.name, icon: <UserIcon />, isHidden: !user },
Нет, я логику сделаю в провайдере, который будет наружу выдавать функцию выхода и состояние авторизации. А кнопка входа лишь маршрутизатор к странице входа. По макету я нажимаю на войти и идет переход на страницу "вход", логики авторизации при этом нет, есть лишь указание пути. 
Если бы вся логика "авторизовывать\деавторизовывать" была бы на одной странице то наверное да.

2024-08-15 21:59 UTC, Quaaludees commented on src/components/FilmCard/FilmCard.jsx
>                      <FavIcon/>
+

2024-08-19 13:47 UTC, Levitinn commented on src/components/Header/Header.jsx
> +        { href: '#', title: user?.name, icon: <UserIcon />, isHidden: !user },
уговорила. молодец))

2024-08-19 13:49 UTC, Levitinn approved these changes

2024-08-19 16:59 UTC, merged