4 data
Quaaludees/react-hw pull request #4
Opened 2024-09-16 23:21 UTC by Quaaludees

2024-09-17 20:38 UTC, Levitinn requested changes
- после авторизации не происходит редирект со страницы авторизации
- на странице авторизации, если нажать на "войти" в меню хедера, попаду на 404
- рейтинг у карточки фильма рендерится, но визуально его нет

2024-09-17 21:18 UTC, Quaaludees commented
![image](https://github.com/user-attachments/assets/a00398cd-b298-4805-8faf-9a1e1a777673)
Редирект идет после авторизации. 
Остальное исправлено!

2024-09-17 21:21 UTC, Quaaludees commented
А пон. Это где не было юзера, тож поправлено.

2024-09-18 15:05 UTC, Levitinn approved these changes

2024-09-19 19:20 UTC, merged